name: multiple_jobs_run
on: schedule
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "welcome to build"

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Test step
        run: echo "welcome to test"

  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Delpoy test
        run: echo "welcome to Deploy"
    
